### PR TITLE
Fix Combo popup size and position

### LINKED ISSUE #90: Combo popup size is not constrained to the screen
Occurred after updating from 2.2 to 2.4, likely caused by ec4d167.

When the combo contains a lot of items, the combo size extends up and out of the screen. Since the size is not constrained, the AutomaticCanvasSize never kicks in and the canvas size never increased. This means you can't scroll to reach the off-screen elements.

My initial solution was to add a `UISizeConstraint` to the combo popup, however there is currently a [bug](https://devforum.roblox.com/t/guiobjectautomaticsize-does-not-respect-uisizeconstraint/2932381) that means this solution does not work.

I think that until this bug is fixed, it would be better to revert to the old behaviour.

image

### PR DESCRIPTION
**Pull request by Tazmondo**
Fixes #90

The commit that edits the demo window can be undone if not desired, but it was useful in testing my solution.

I'm not sure if adding the `UIListLayout` to the Combo type fits with how the codebase is structured, please correct me if there's a better way of getting a reference to the `UIListLayout`.

The idea behind how the positioning works is:
- Try and extend the list downwards first.
- If this results in it going off the screen, and there is more space above than there is below (the origin is in the bottom half of the screen), then extend upwards instead, so as much of the selection as possible is visible. 
- If there is more space below, then extend downwards as normal.
- In both cases, the size is constrained to the edge of the screen so you can scroll to see all the available options.

Also I've noticed there is similar popup behaviour for the Menu widget - I have not investigated or used it myself but it may benefit from similar changes being made to it?

### CODE REVIEW

**Comment by Tazmondo** [comment]
Demo video of the functionality

https://github.com/user-attachments/assets/d028fbbd-767d-456c-8a81-38dfe0339b5f

**Comment by Tazmondo** [comment]
Demo video:


https://github.com/user-attachments/assets/d1facb67-bf3e-411e-b7ad-74e308bb738a

**Comment by Tazmondo** [comment]
Seems like setting the AutomaticSize to Y just overrides the size property and brings us back to square one, with the combo going off-screen again when there are many elements.

It would be ideal if we could recalculate the size whenever the contents are changed, but I'm not sure if there's already some infrastructure to allow for that or if it would have to be added in. I see a ChildAdded event here but we'd need a DescendantAdded and DescendantRemoved.

An alternative would be to, while there is a combo open, just cache the `UIListLayout.AbsoluteContentSize.Y` value, check if it has changed each frame, and if it has then recalculate the size and cache the new value.

**Review by Tazmondo — COMMENTED** [review]
Causes combo menu to go off-screen again when there are too many elements

**Comment by Tazmondo** [comment]
This should fix it while hopefully fitting the style of the codebase? Performance should also be fine, the `UpdateChildContainerTransform` is only run once when the combo opens or when the contents change.

**Comment by Tazmondo** [comment]
Demo Video:


https://github.com/user-attachments/assets/e07074fd-fa26-4054-a529-ca65c2d90347


The combo menu flipping upwards after you extend the contents doesn't feel *great*, but I think it'd also feel pretty bad if it didn't flip and a large number of items are now off the screen, so it should be fine to leave it as it is.

**Comment by JonathanOrd** [comment]
Yeah, I realised this issue, but forgot to add a comment to let you know. I was hoping to use the UISizeConstraint within to limit the size whilst also allowing the AutomaticSize to work. However, there is a bug which means that the AutomaticSize does not respect the UISizeConstraint, https://devforum.link/1391918.

Instead, I would be happy to just leave the odd behaviour, since closing and reopening the combo will always resize it. I don't know whether I would rather have a function constantly checking for updates, or just be happy leaving it slightly broken (for now).

File: lib/widgets/Combo.lua [hunk 1]
```diff
@@ -130,34 +130,52 @@ return function(Iris: Types.Internal, widgets: Types.WidgetUtility)
...
         end
+
         ChildContainer.AnchorPoint = anchor
         ChildContainer.Position = UDim2.fromOffset(x, y)
+
+        local height = math.min(contentsSize, distanceToScreen)
+        ChildContainer.Size = UDim2.fromOffset(PreviewContainer.AbsoluteSize.X, height)
     end
 
+    table.insert(Iris._postCycleCallbacks, function()
```
Comment (JonathanOrd) [inline lib/widgets/Combo.lua:170]: I don't know whether there is a better option than just to constantly poll.

**Review by JonathanOrd — COMMENTED** [review]
I don't know of any better way of handling this. And whether it's just better to leave this minor inconvenience in?

**Review by SirMallard — COMMENTED** [review]
Yeah, I realised this issue, but forgot to add a comment to let you know. I was hoping to use the UISizeConstraint within to limit the size whilst also allowing the AutomaticSize to work. However, there is a bug which means that the AutomaticSize does not respect the UISizeConstraint, https://devforum.link/1391918.

Instead, I would be happy to just leave the odd behaviour, since closing and reopening the combo will always resize it. I don't know whether I would rather have a function constantly checking for updates, or just be happy leaving it slightly broken (for now).

**Comment by Tazmondo** [comment]
Yeah that probably would have been the ideal solution, but alas.

As for whether to keep the odd behaviour or keep the function, I do lean towards keeping the function there.

I can definitely see how it doesn't really fit with Iris' approach to things, and isn't an ideal solution, but I think it's better than settling for janky behaviour.

The pattern of some widget type running code each frame is already used for tables. (https://github.com/Tazmondo/Iris/blob/main/lib/widgets/Table.lua#L9-L13)

The performance impact of a couple if statements and a property index each frame, and only while you have a combo open, should be pretty negligible. The more expensive part is only run when it needs to.

Regardless, if you'd like I can revert the change.

**Review by SirMallard — APPROVED** [review]
Yeah, it's a Roblox issue that prevents it from having a better example, so we'll accept the slight cost. But I like the caching.
